apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-application
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=3
  nfs:
    path: /files
    server: 10.10.2.4
